stages:
  train_bert_length_predictors:
    foreach:
      - 10
      - 50
    do:
      cmd: >
        python lenght_prediction.py
        --data_dir data/lmsys_vicuna-13b_preview0_${item}K
        --model_name google-bert/bert-base-uncased
        --output_dir results/bert_length_predictor_${item}
        --batch_size 5
        --seed 42
        --use_wandb
        --wandb_project output-length-prediction
        --do_eval
        --do_train

  generate_trail_dataset:
    cmd: >
      python generate_dataset.py
      --model meta-llama/Meta-Llama-3-8B-Instruct
      --max_length 512
      --dataset tatsu-lab/alpaca
      --split train[:1000]
      --output /lustre/pd01/hpc-tomasznaskret-1742832160/trail_dataset_layers2.pt
    deps:
      - generate_dataset.py
        
  train_embeddings_predictors_trail:
    foreach:
      - 'layer_8'
      - 'layer_9'
      - 'layer_10'
      - 'layer_11'
      - 'layer_12'
      - 'layer_13'
      - 'layer_14'
      - 'layer_15'
    do:
      cmd: >
        python embedings_prediction2.py
        --data_path /lustre/pd01/hpc-tomasznaskret-1742832160/trail_dataset_layers2.pt
        --layer_name ${item}
        --output_dir results/embeddings_predictor_trail_${item}
        --use_wandb
        --do_train
        --do_eval
        --batch_size 50
        --learning_rate 1e-5
        --num_epochs 30
        --seed 42
        --use_amp

  train_embeddings_predictors_agg:
    foreach:
      - {layers: 'layer_10 layer_11 layer_12', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12', agg: 'sum'}
      - {layers: 'layer_11 layer_12 layer_13', agg: 'sum'}
      - {layers: 'layer_12 layer_13 layer_14', agg: 'sum'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_9 layer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_8 layer_9 zlayer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_9 layer_10 layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_8 layer_9 layer_10 layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12', agg: 'sum'}
      - {layers: 'layer_11 layer_12 layer_13', agg: 'sum'}
      - {layers: 'layer_12 layer_13 layer_14', agg: 'sum'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_9 layer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_8 layer_9 zlayer_10 layer_11 layer_12 layer_13', agg: 'mean'}
      - {layers: 'layer_9 layer_10 layer_11 layer_12 layer_13 layer_14', agg: 'mean'}
      - {layers: 'layer_10 layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'mean'}
      - {layers: 'layer_8 layer_9 layer_10 layer_11 layer_12 layer_13 layer_14 layer_15', agg: 'sum'}
    do:
      cmd: >
        python embedings_prediction.py
        --data_path /lustre/pd01/hpc-tomasznaskret-1742832160/trail_dataset_layers2.pt
        --layers ${item.layers}
        --aggregation ${item.agg}
        --output_dir results/embeddings_predictor_${item.agg}
        --do_train
        --do_eval
        --use_wandb
        --wandb_project embeddings-length-predictor
        --batch_size 50
        --learning_rate 1e-5
        --num_epochs 30
        --seed 42
        --use_amp
      deps:
        - embedings_prediction.py

  train_graph_regressors_thresholds:
    foreach:
      - { edge_mode: 'sequential'}
      - { edge_mode: 'fully_connected'}
    do:
      cmd: >
        python graph_regressor.py
        --data_path /lustre/pd01/hpc-tomasznaskret-1742832160/trail_dataset_layers2.pt
        --output_dir results/graph_regressor_${item.edge_mode}
        --do_train
        --do_eval
        --batch_size 16
        --learning_rate 1e-3
        --num_epochs 30
        --hidden_dim 128
        --seed 42
        --use_amp
        --num_workers 4
        --edge_mode ${item.edge_mode}
      deps:
        - graph_regressor.py
